#%RAML 1.0 Library
traits:
  headers: !include ../exchange_modules/38c011ae-c7fb-4f18-ad74-bbe191ed62cf/common-header-traits/1.0.1/common-header-traits.raml
  errorCodes: !include ../exchange_modules/38c011ae-c7fb-4f18-ad74-bbe191ed62cf/common-header-traits/1.0.1/common-header-traits.raml